mysql.driver=com.mysql.cj.jdbc.Driver
mysql.url=jdbc:mysql://localhost:3306/school_spring?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
mysql.username=fisher
mysql.password=2580852yzc
